notifications:
  slack: $slack
sudo: required
language: node_js
node_js:
    - "9.7.1"
install:
  - npm i
script:
  - npx ng lint
  - npx ng test @angeeks/testing --watch=false
  - npx ng build @angeeks/testing --prod
  - npx ng test testing --watch=false
  - npx ng build testing --prod --base-href testing
cache:
    directories:
      - node_modules
before_deploy:
  - cp README.md dist/angeeks/testing
  - cd dist/angeeks/testing
deploy:
  - provider: npm
    email: $npmEmail
    api_key: $npm
    skip_cleanup: true
    keep-history: true
    tag: latest
    on:
      branch: release
